version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "dev.w2018.thinkpiecepartners.com"
phases:
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive --acl public-read
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: '.'
    discard-paths: yes